### ISSUE TITLE
Existing user created as null email

### ISSUE THREAD

**Issue by BKdilse** [tylerjohneddy/ExchangeBackend#12]
When creating a new user, who is already registered, a new null email user is created.

User table contains null user.
Wallet table creates an additional wallet for the user, with the valid email address.

**Comment by tylerjohneddy** [comment]
@BKdilse if you are happy with this could you close the issue

**Comment by BKdilse** [comment]
Confirmed fixed, but there is no feedback.  Should we have feedback, stating "That user account already exists!" ?

**Comment by tylerjohneddy** [comment]
No I don't think we should, if we add this functionality someone with malicious intent could try loads of emails till it returns with that information and they would have found a valid username

**Comment by BKdilse** [comment]
good point.  This is done then :)
